config/routes.rb
Rails.application.routes.draw do
  root to: 'tickets#stats'

  get 'tickets/index'

  resources :events do
    resources :ticket_types
  end

  resource :sessions, only: [:new, :create, :destroy]

  namespace :api do
    resource :tickets, only: [] do
      post :dj
      post :band
      post :both
    end

    resource :tokens, only: [:create, :destroy]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :delete]

  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new event_params

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find params[:id]
  end

  def event_params
    params.require(:event).permit(
      :name,
      :description,
      :start_date,
      :end_date
    )
  end
end

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    div.error
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this asset from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message
  div.field
    = f.label :name
    = f.text_field :name, placeholder: 'Event Name'
  div.field
    = f.label :start_date
    = f.date_select :start_date
  div.field
    = f.label :end_date
    = f.date_select :end_date
  div.field
    = f.label :description
    = f.text_area :description
  div.field
    = f.submit

app/views/events/index.html.slim
h1
  | Events
section
  button
    = link_to 'New Event', new_event_path
section
  table
    thead
      tr
        th Name
        th Start Date
        th Stop Date
    tbody
      -@events.each do |event|
        tr
          td
            = link_to event.name, event_path(event)
          td
            = event.start_date
          td
            = event.end_date
    

app/views/events/new.html.slim
= render 'form'